spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: chat-bot-service
          uri: lb://chat-bot-service
          predicates:
            - Path=/chatbot/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 9000
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS}