spring:
  application:
    name: restaurant-gateway-service
  cloud:
    gateway:
    discovery:
      locator:
        enabled: true
    routes:
      - id: customers
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
      - id: restaurants
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurant/**
server:
  port: ${app_port}
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8900/eureka